import { createElement } from 'lwc';
import Lwc_LDS_IMP_DELETE from 'c/lwc_LDS_IMP_DELETE';

describe('c-lwc-l-d-s-i-m-p-delete', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-l-d-s-i-m-p-delete', {
            is: Lwc_LDS_IMP_DELETE
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});