import { createElement } from 'lwc';
import Lwc_eg_LDS_RecordForm from 'c/lwc_eg_LDS_RecordForm';

describe('c-lwc-eg-l-d-s-record-form', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-eg-l-d-s-record-form', {
            is: Lwc_eg_LDS_RecordForm
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});